[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[lib]
name = "crawler"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
base64 = { version = "0.22.1" }
chrono = { version = "0.4.41", features = ["clock"] }
config = { version = "0.15.11", optional = true, default-features = false, features = ["toml"] }
form_urlencoded = { version = "1.2.1" }
log = { version = "0.4.27" }
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tokio = { version = "1.45.1", features = ["full"] }

[features]
config = ["dep:config"]
cache = []
